#!/bin/bash -i
alias webhome='cd ~/Desktop/webdesign && ls'
alias railshome='cd ~/Desktop/webdesign/rails-apps/ && ls'
alias Home='cd ~ && ls'
alias bashrc='nano ~/.bashrc'
alias root='sudo su'
alias dbm='rake db:migrate'
alias Desktop='cd ~/Desktop && ls'
alias abc='echo a b c d e f g h i j k l m n o p q r s t u v w x y z'
alias bashprofile='nano ~/.bash_profile'
alias up='cd .. && ls'
